In [1]:
# Transform dict to json data:
import json
from tqdm import tqdm
import pandas as pd

athlete_bio = pd.read_csv('./Olympics Data From 1986 to 2022/Olympic_Athlete_Bio.csv')
athlete_events_result = pd.read_csv('./Olympics Data From 1986 to 2022/Olympic_Athlete_Event_Results.csv')
edition_medal_per_country = pd.read_csv('./Olympics Data From 1986 to 2022/Olympic_Games_Medal_Tally.csv')
olympic_games_description = pd.read_csv('./Olympics Data From 1986 to 2022/Olympics_Games.csv')
olympic_country = pd.read_csv('./Olympics Data From 1986 to 2022/Olympics_Country.csv')

In [2]:
athlete_bio

,athlete_id,name,sex,born,height,weight,country,country_noc,description,special_notes
0,16809,Károly Teppert,Male,1891-07-20,na,na,Hungary,HUN,Károly Teppert started competing in cycling in...,na
1,43737,Andrzej Socharski,Male,1947-08-31,173.0,72,Poland,POL,na,Listed in Olympians Who Won a Medal at the Wor...
2,50147,Nathalie Wunderlich,Female,1971-06-03,170.0,50,Switzerland,SUI,na,na
3,5085,Miha Lokar,Male,1935-09-10,182.0,76,Yugoslavia,YUG,na,Listed in Olympians Who Won a Medal at the Eur...
4,136329,Austin Hack,Male,1992-05-17,203.0,100,United States,USA,na,na
...,...,...,...,...,...,...,...,...,...,...
155026,25136,Jean Palluch,Male,1923-12-23,180.0,80,France,FRA,na,na
155027,701697,Hendrik Mangelaar Meertens,Male,1908-09-30,na,na,Netherlands,NED,"Hendrik Mangelaar Meertens, usually known as “...",Listed in Olympians Who Were Killed or Missing...
155028,11757,Jo Hyeong-Won,Male,1936-07-12,173.0,65,Republic of Korea,KOR,na,na
155029,21666,Raúl Maroto,Male,1965-09-05,190.0,76,Spain,ESP,na,Listed in Olympians Who Won a Medal at the Med...
155030,72486,Shizo Kanakuri,Male,1891-08-20,170.0,64,Japan,JPN,Kanakuri had a weak constitution as a child un...,na

In [3]:
athlete_events_result

,edition,edition_id,country_noc,sport,event,result_id,athlete,athlete_id,pos,medal,isTeamSport,year_of_games
0,1908 Summer Olympics,5,ANZ,Athletics,"100 metres, Men",56265,Ernest Hutcheon,64710,DNS,na,False,1908
1,1908 Summer Olympics,5,ANZ,Athletics,"400 metres, Men",56313,Henry Murray,64756,DNS,na,False,1908
2,1908 Summer Olympics,5,ANZ,Athletics,"800 metres, Men",56338,Harvey Sutton,64808,3 h8 r1/2,na,False,1908
3,1908 Summer Olympics,5,ANZ,Athletics,"800 metres, Men",56338,Guy Haskins,922519,DNS,na,False,1908
4,1908 Summer Olympics,5,ANZ,Athletics,"800 metres, Men",56338,Joseph Lynch,64735,DNS,na,False,1908
...,...,...,...,...,...,...,...,...,...,...,...,...
314902,2022 Winter Olympics,62,NED,Bobsleigh,"Monobob, Women",19019671,Karlien Sleper,148662,16,na,False,2022
314903,2022 Winter Olympics,62,SVK,Bobsleigh,"Monobob, Women",19019671,Viktória Čerňanská,138683,17,na,False,2022
314904,2022 Winter Olympics,62,KOR,Bobsleigh,"Monobob, Women",19019671,Kim Yu-Ran,137542,18,na,False,2022
314905,2022 Winter Olympics,62,JAM,Bobsleigh,"Monobob, Women",19019671,Jazmine Fenlator-Victorian,128682,19,na,False,2022
314906,2022 Winter Olympics,62,UKR,Bobsleigh,"Monobob, Women",19019671,Lidiya Hunko,149047,20,na,False,2022

In [4]:
def get_country_info_from_noc(noc_code):
    country_name = olympic_country[olympic_country['country_noc'] == noc_code]['real_name'].values[0]
    lat = olympic_country[olympic_country['country_noc'] == noc_code]['lat'].values[0]
    long = olympic_country[olympic_country['country_noc'] == noc_code]['long'].values[0]
    inter_code = olympic_country[olympic_country['country_noc'] == noc_code]['inter_code'].values[0]
    
    info= {'country_name': country_name,
              'inter_code': inter_code,
              'coordinate': [lat, long]}
    return info
    
def get_edition_info_from_id(id):
    year = olympic_games_description[olympic_games_description['edition_id'] == id]['year'].values[0]
    edition_name = olympic_games_description[olympic_games_description['edition_id'] == id]['edition'].values[0]
    city = olympic_games_description[olympic_games_description['edition_id'] == id]['city'].values[0]
    country_of_game_noc = olympic_games_description[olympic_games_description['edition_id'] == id]['country_noc'].values[0]
    country_info = get_country_info_from_noc(country_of_game_noc)
    info = {'year': year, 
            'edition_name': edition_name, 
            'city': city, 
            'country_of_game': country_info['country_name'], 
            'inter_code': country_info['inter_code'], 
            'coordinate': country_info['coordinate'] }
    return info

def get_athlet_info_from_id(id):
    name = athlete_bio[athlete_bio['athlete_id'] == id]['name'].values[0]
    born = athlete_bio[athlete_bio['athlete_id'] == id]['born'].values[0]
    country_of_birth_noc = athlete_bio[athlete_bio['athlete_id'] == id]['country_noc'].values[0]
    country_info = get_country_info_from_noc(country_of_birth_noc)
    
    country_of_birth = country_info['country_name']
    country_coordinates = country_info['coordinate']
    inter_code = country_info['inter_code']
    
    info = {'name': name, 
            'born': born,
            'country_of_birth': country_of_birth, 
            'inter_code': inter_code, 
            'coordinate': country_coordinates}
    
    return info

def find_athlete_participation_from_a_year(year):
    athlete_list = []
    for index, row in athlete_events_result.iterrows():
        if row['year'] > year:
            athlete_list.append(row['athlete_id'])
    return athlete_list


def find_athlete_participation_from_a_country(inter_code):
    athlete_list = []
    
    for index, row in athlete_events_result.iterrows():
        info = get_country_info_from_noc(row['country_noc'])
        if info['inter_code'] == inter_code:
            athlete_list.append(row['athlete_id'])
            
    return athlete_list

# [
#     {type: "LineString", coordinates: [[100, 60], [-60, -30]]},
#     {type: "LineString", coordinates: [[-60, -30], [10, -20]]},
#     {type: "LineString", coordinates: [[10, -20], [130, -30]]} 
#   ]

def build_athlete_path(athlete_id,json_data,year=None):
    link = []
    athlete_info = json_data[str(athlete_id)]
    link.append({'type': 'LineString', 
                 'coordinates': [athlete_info['country_of_birth_coordinate'], 
                                 athlete_info['country_of_game_coordinate']]})
    
    for game_year,game_details in athlete_info['games_participation'].items():
        if year is not None:
            if game_year >= year:
                link.append({'type': 'LineString', 
                     'coordinates': [game_details['country_of_game_coordinate'], 
                                     game_details['country_of_birth_coordinate']]})
        else:
            link.append({'type': 'LineString', 
                     'coordinates': [game_details['country_of_game_coordinate'], 
                                     game_details['country_of_birth_coordinate']]})
    if year is not None:
        return False if len(link) == 1 else link
    
    return link

In [5]:

# Construct each athlete participation
# we need : ahtlete name
#           athlete id
#           athlete country coordonate
#           Games id
#           Games participation {year : coordonate of the host country}

athlete_data_parcours = {}

from_index = 0
# Iterate over each athlete in athlete_events_result
for athlete_id, games_id, isTeamSport, medal, sport_type in tqdm(zip(athlete_events_result['athlete_id'][from_index:]
                           ,athlete_events_result['edition_id'][from_index:]
                           ,athlete_events_result['isTeamSport'][from_index:]
                           ,athlete_events_result['medal'][from_index:]
                           ,athlete_events_result['sport'][from_index:])):
    

    try:
        athlete_info = get_athlet_info_from_id(athlete_id)
        
        # About the athlete
        athlete_name = athlete_info['name']
        athlete_country_name = athlete_info['country_of_birth']
        athlete_country_code = athlete_info['inter_code']
        athlete_country_coord = athlete_info['coordinate']
        
        # About the games
        games_info = get_edition_info_from_id(games_id)
        games_name = games_info['edition_name']
        games_year = games_info['year']
        games_country = games_info['country_of_game']
        games_country_code = games_info['inter_code']
        games_country_coord = games_info['coordinate']
        
        
        if str(athlete_id) in athlete_data_parcours.keys():
            if sport_type not in athlete_data_parcours[str(athlete_id)]['sport_type']:
                athlete_data_parcours[str(athlete_id)]['sport_type'].append(sport_type)
            
            if str(games_year) in athlete_data_parcours[str(athlete_id)]['games_participation'].keys():
                    
                gold_count = athlete_data_parcours[str(athlete_id)]['games_participation'][str(games_year)]['gold']
                silver_count = athlete_data_parcours[str(athlete_id)]['games_participation'][str(games_year)]['silver']
                bronze_count = athlete_data_parcours[str(athlete_id)]['games_participation'][str(games_year)]['bronze']
                
                athlete_data_parcours[str(athlete_id)]['games_participation'][str(games_year)] = {
                'games_name' : games_name,
                'games_id' : games_id,
                'games_country_coord' : games_country_coord,
                'games_country_code' : games_country_code,
                'gold' : gold_count + 1 if medal == 'Gold' else gold_count,
                'silver' : silver_count + 1 if medal == 'Silver' else silver_count,
                'bronze' : bronze_count + 1 if medal == 'Bronze' else bronze_count
            }
            else:
                athlete_data_parcours[str(athlete_id)]['games_participation'][str(games_year)] = {
                'games_name' : games_name,
                'games_id' : games_id,
                'games_country_coord' : games_country_coord,
                'games_country_code' : games_country_code if games_country_code else "NA",
                'gold' : 1 if medal == 'Gold' else 0,
                'silver' : 1 if medal == 'Silver' else 0,
                'bronze' : 1 if medal == 'Bronze' else 0
            }
                    
        else:
            athlete_data_parcours[str(athlete_id)] = {
            'athlete_name' : athlete_name,
            'sport_type' : [sport_type],
            'athlete_country_name' : athlete_country_name,
            'athlete_country_code' : athlete_country_code,
            'athlete_country_coord' : athlete_country_coord,
            'games_participation' : {str(games_year) : {
                'games_name' : games_name,
                'games_id' : games_id,
                'games_country_coord' : games_country_coord,
                'games_country_code' : games_country_code,
                'gold' : 1 if medal == 'Gold' else 0,
                'silver' :   1 if medal == 'Silver' else 0,
                'bronze' :   1 if medal == 'Bronze' else 0
                }
            }
        }
    except Exception as e:
        print(e)
        print(athlete_info)
        print(games_info)

0it [00:00, ?it/s]

234637it [49:34, 85.81it/s]

index 0 is out of bounds for axis 0 with size 0
{'name': 'Eberardo Schmalzl', 'born': '1950-06-12', 'country_of_birth': 'Italy', 'inter_code': 'IT', 'coordinate': [42.83, 12.83]}
{'year': 1972, 'edition_name': '1972 Winter Olympics', 'city': 'Sapporo', 'country_of_game': 'Japan', 'inter_code': 'JP', 'coordinate': [36.0, 138.0]}

277983it [55:12, 209.15it/s]

index 0 is out of bounds for axis 0 with size 0
{'name': 'Bruno Jutzeler', 'born': '1946-01-01', 'country_of_birth': 'Switzerland', 'inter_code': 'CH', 'coordinate': [47.0, 8.0]}
{'year': 1972, 'edition_name': '1972 Summer Olympics', 'city': 'München', 'country_of_game': 'Germany', 'inter_code': 'DE', 'coordinate': [51.0, 9.0]}

278159it [55:13, 212.75it/s]

index 0 is out of bounds for axis 0 with size 0
{'name': 'Michel Broillet', 'born': '1944-07-15', 'country_of_birth': 'Switzerland', 'inter_code': 'CH', 'coordinate': [47.0, 8.0]}
{'year': 1976, 'edition_name': '1976 Summer Olympics', 'city': 'Montréal', 'country_of_game': 'Canada', 'inter_code': 'CA', 'coordinate': [60.0, -95.0]}

314907it [58:11, 90.18it/s]

In [7]:
# Use json.dump to write dict_data to a JSON file
with open('athlete_data_medals.json', 'w') as f:
    json.dump(athlete_data_parcours,f,ensure_ascii=True, indent=0)